version: '3.9'

services:
  redis:
    image: redis:8.0.3
    container_name: syntaxfa_redis
    hostname: ${REDIS_HOST:?error}
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:?error} --port ${REDIS_PORT:?error}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:?error}
      REDIS_PORT: ${REDIS_PORT:?error}
    volumes:
      - type: bind
        source: ./redis.conf
        target: /usr/local/etc/redis.conf
        read_only: true
        # ./redis.conf:/usr/local/etc/redis.conf:ro
    ports:
      - ${REDIS_PORT:?error}:${REDIS_PORT:?error}
