# Generated by Django 5.2 on 2025-06-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='user id')),
                ('access_uuid', models.UUIDField(db_index=True, unique=True, verbose_name='access uuid')),
                ('refresh_uuid', models.UUIDField(db_index=True, unique=True, verbose_name='refresh uuid')),
            ],
            options={
                'verbose_name': 'User Auth',
                'verbose_name_plural': 'User Auths',
                'ordering': ('-id',),
            },
        ),
    ]
